# Generated by Django 2.1.7 on 2019-03-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('position', models.PositiveSmallIntegerField(blank=True, verbose_name='Position')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'db_table': 'core_block_type',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'db_table': 'core_category',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('position', models.IntegerField(blank=True, default=1, verbose_name='Position')),
                ('is_default_home_page', models.BooleanField(default=False, verbose_name='Use page as default home page')),
                ('featured_image', models.URLField(blank=True, verbose_name='Featured image')),
                ('categories', models.ManyToManyField(blank=True, db_table='core_page_categories', related_name='page_set', to='core.Category', verbose_name='Categories')),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_page_set', to='core.Page', verbose_name='Parent page')),
            ],
            options={
                'db_table': 'core_page',
                'ordering': ['post_type__name', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('language', models.CharField(max_length=2, verbose_name='Language')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_translation_set', to='core.Page')),
            ],
            options={
                'db_table': 'core_page_translation',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'db_table': 'core_post_type',
            },
        ),
        migrations.CreateModel(
            name='ImgurAlbumBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'db_table': 'core_imgur_album_block',
            },
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='ImgurImageBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'db_table': 'core_imgur_image_block',
            },
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='PageJumpsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Category')),
                ('post_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PostType', verbose_name='Post types')),
            ],
            options={
                'db_table': 'core_page_jumps_block',
            },
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='StaticBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'db_table': 'core_static_block',
            },
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'db_table': 'core_text_block',
            },
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'db_table': 'core_video_block',
            },
            bases=('core.block',),
        ),
        migrations.AddField(
            model_name='page',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PostType', verbose_name='Post type'),
        ),
        migrations.AddField(
            model_name='block',
            name='page_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_set', to='core.PageTranslation'),
        ),
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.BlockType'),
        ),
        migrations.AlterUniqueTogether(
            name='pagetranslation',
            unique_together={('language', 'url'), ('language', 'page')},
        ),
    ]
