# Generated by Django 2.1.7 on 2019-04-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagejumpsblock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pagejumpsblock',
            name='post_type',
        ),
        migrations.AddField(
            model_name='pagejumpsblock',
            name='pages',
            field=models.ManyToManyField(blank=True, db_table='core_page_jumps_block_pages', related_name='_pagejumpsblock_pages_+', to='core.Page', verbose_name='Pages'),
        ),
    ]
