# Generated by Django 2.1.7 on 2019-04-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190401_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='page',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='page',
            name='post_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PostType',
        ),
    ]
