# Generated by Django 2.1.7 on 2019-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190401_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('position',)},
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='Default', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
