# Generated by Django 2.1.7 on 2019-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190401_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetranslation',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='seo_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='seo_thumbnail',
            field=models.URLField(blank=True, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='pagejumpsblock',
            name='pages',
            field=models.ManyToManyField(db_table='core_page_jumps_block_pages', related_name='_pagejumpsblock_pages_+', to='core.Page', verbose_name='Pages'),
        ),
    ]
