# Generated by Django 2.1.7 on 2019-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190402_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetranslation',
            name='seo_name',
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='seo_thumbnail',
            field=models.URLField(blank=True, verbose_name='SEO thumbnail'),
        ),
    ]
