# Generated by Django 2.1.7 on 2019-04-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190402_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetranslation',
            name='seo_thumbnail',
        ),
    ]
