# Generated by Django 2.1.7 on 2019-04-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_pagetranslation_seo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetranslation',
            name='seo_description',
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Translated name'),
        ),
    ]
