# Generated by Django 2.1.7 on 2019-05-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190405_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetranslation',
            name='action_redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Page', verbose_name='Action redirect'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='action_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Action title'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Translated description'),
        ),
    ]
