# Generated by Django 2.1.7 on 2019-05-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190516_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_in_bottom_menu',
            field=models.BooleanField(default=False, verbose_name='Include in bottom menu'),
        ),
    ]
