# Generated by Django 2.1.7 on 2019-05-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_page_is_in_bottom_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('coordinates', models.CharField(max_length=255, verbose_name='Coordinates')),
            ],
            options={
                'db_table': 'core_map_block',
            },
            bases=('core.block',),
        ),
    ]
