name: testing-and-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REDIS_URL: ${{ secrets.REDIS_RUL }}
      SECRET: ${{ secrets.SECRET }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      TRAKT_TV_CALLBACK_URL: ${{ secrets.TRAKT_TV_CALLBACK_URL }}
      TRAKT_TV_CLIENT_ID: ${{ secrets.TRAKT_TV_CLIENT_ID }}
      TRAKT_TV_CLIENT_SECRET: ${{ secrets.TRAKT_TV_CLIENT_SECRET }}
    defaults:
      run:
        working-directory: ./packages/server
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm ci
    - run: npm test
  deploy:
    needs: [backend-tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s0/git-publish-subdir-action@v2.4.0
      env:
        REPO: self
        BRANCH: heroku
        FOLDER: packages/server
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
