name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ENV_VARS: ${{ secrets.ENV_VARS }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "bibliobrain"
          heroku_email: ${{ secrets.HEROKU_ACCOUNT_EMAIL }}
          justlogin: true
      - name: inject env variables and security token
        run: |
          echo -e $ENV_VARS > ./.configrc
          echo -e "${{ secrets.ACCESS_TOKEN_PUBLIC }}" > ./security/accessTokenPublic.pem
          echo -e "${{ secrets.ACCESS_TOKEN_PRIVATE }}" > ./security/accessTokenPrivate.pem
          echo -e "${{ secrets.REFRESH_TOKEN_PUBLIC }}" > ./security/refreshTokenPublic.pem
          echo -e "${{ secrets.REFRESH_TOKEN_PRIVATE }}" > ./security/refreshTokenPrivate.pem
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: push to heroku
        run: |
          heroku container:login
          heroku git:remote -a bibliobrain
          heroku container:push web
          heroku container:release web
